### ISSUE TITLE
Don't alert() an error if "Cancel" is clicked on the "Add Preview Size" dialog.

### ISSUE THREAD

**Issue by itstiraboschi** [SongSing/avatarcropper#3]
Currently, clicking "Add Preview Size" then clicking "Cancel" returns an error about invalid input, instead it should silently do nothing. Changing this (in js/discordphoto.js):

    var size = parseInt(prompt("Enter a custom size like 256"));
        if (isNaN(size) || size <= 0) {
            alert("Bad size make sure its a number over 0");
        } else {
                createPreviewCanvas(size);
        }

to this:

    var size = parseInt(prompt("Enter a custom size (e.g. 256)"));
        if (isNaN(size) || size == ""){
            return   
        } else if(size <= 0){
            alert("Invalid size, make sure you entered a number that is above 0.");
        } else {
             createPreviewCanvas(size);
        }

or something similar, would work.

**Comment by SongSing** [comment]
u rite

**Comment by SongSing** [comment]
fixed
